services:
  home:
    container_name: home
    build:
      context: ../home
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9000:9000
    networks:
      - gateflow_network

networks:
  gateflow_network:
    external: true
